FA.AtmSystem.Web/Controllers/ATMController.cs
using FA.AtmSystem.Cards.ViewModels;
using FA.AtmSystem.Core.Models;
using FA.AtmSystem.Web.Infrastructures;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FA.AtmSystem.Web.Controllers
{
    public class ATMController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ATMController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [Authorize]
        public IActionResult Index()
        {
            TempData["CardNo"] = HttpContext.Session.GetString("CardNo");
            
            return View();
        }

        [HttpGet]
        public IActionResult EjectCard()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SwallowCard()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ValidateWait()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ValidateCard()
        {
            CardValidateVM obj = new CardValidateVM();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValidateCard(CardValidateVM obj)
        {
            Card objCard = await _unitOfWork.ATMRepository.ValidateCardAsync(StaticDetails.ATMAPIPath + "ValidateCard/", obj, HttpContext.Session.GetString("JWTokenATM"));
            
            if (objCard.CardNo == null)
            {
                return RedirectToAction("EjectCard");
            }

            // Reset Card Attempt
            await _unitOfWork.ATMRepository.ResetCardAttemptAsync(StaticDetails.ATMAPIPath + "ResetCardAttempt/", obj, HttpContext.Session.GetString("JWTokenATM"));

            TempData["CardNo"] = objCard.CardNo;
            TempData["Attempt"] = "0";
            return RedirectToAction("ValidateCardPIN");
        }

        [HttpGet]
        public IActionResult ValidateCardPIN()
        {
            CardValidatePINVM obj = new CardValidatePINVM();
            
            return View(obj);
        }

        public IActionResult Goodbye()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValidateCardPIN(CardValidatePINVM obj)
        {
            // Value of objCard is empty if valid PIN failed
            Card objCard = await _unitOfWork.ATMRepository.ValidateCardPINAsync(StaticDetails.ATMAPIPath + "ValidatePIN/", obj, HttpContext.Session.GetString("JWTokenATM"));
            CardValidateVM cardAPIInput = new CardValidateVM();
            cardAPIInput.CardNo = obj.CardNo;

            // increaseCard is always a card from DB
            Card increaseCard =  await _unitOfWork.ATMRepository.IncreaseCardAttemptAsync(StaticDetails.ATMAPIPath + "IncreaseCardAttempt/", cardAPIInput, HttpContext.Session.GetString("JWTokenATM"));

            TempData["CardNo"] = obj.CardNo;
            TempData["Attempt"] = "0";
            if (increaseCard.Attempt > 0) 
            {
                TempData["Attempt"] = "1";
            }
            if (objCard.Token == null)
            {
                // objCard.Attempt++;
                if (increaseCard.Attempt > 2)
                {
                    await _unitOfWork.ATMRepository.SwallowCardAsync(StaticDetails.ATMAPIPath + "SwallowCard/", cardAPIInput, HttpContext.Session.GetString("JWTokenATM"));
                    return RedirectToAction("SwallowCard");
                }
                return RedirectToAction("ValidateCardPIN");
            }

            // Reset Card Attempt
            await _unitOfWork.ATMRepository.ResetCardAttemptAsync(StaticDetails.ATMAPIPath + "ResetCardAttempt/", cardAPIInput, HttpContext.Session.GetString("JWTokenATM"));

            // Claim identity
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, objCard.CardNo));
            identity.AddClaim(new Claim(ClaimTypes.Sid, objCard.PIN));
            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

            // Store Token and Card No in Session
            HttpContext.Session.SetString("JWToken", objCard.Token);
            HttpContext.Session.SetString("CardNo", objCard.CardNo);
            HttpContext.Session.SetString("PIN", objCard.PIN);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString("JWToken", "");
            return RedirectToAction("Index", "Home");
        }


    }
}

FA.AtmSystem.Web/Controllers/CustomerController.cs
using FA.AtmSystem.Web.Infrastructures;
using FA.AtmSystem.Web.IRepositories;
using FA.AtmSystem.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FA.AtmSystem.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CustomerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> EnterInput()
        {
            return View();
        }

        public async Task<IActionResult> WithDrawMoney(string withdrawAmmount)
        {
            if (String.IsNullOrEmpty(withdrawAmmount))
            {
                TempData["ErrorMessages"] = "Enter amount money you want to withdraw. Number you enter must be divisible to 50.0000.";
                return RedirectToAction(nameof(EnterInput));
            }
            while (withdrawAmmount.IndexOf(".") != -1)
            {
                withdrawAmmount = withdrawAmmount.Replace(".", "");
            }
            decimal WithDrawMoney = decimal.Parse(withdrawAmmount);
            
            string cardNo = HttpContext.Session.GetString("CardNo");
            int ATMId = int.Parse(HttpContext.Session.GetString("ATMId"));
            var result=await _unitOfWork.CustomerRepository.WithDraw(StaticDetails.CustomerAPIPath, ATMId, WithDrawMoney, cardNo, HttpContext.Session.GetString("JWToken"));
            if (result.Description==null)
            {
               
                return View();
            }
            TempData["ErrorMessages"] =result.Description.ToString();
            return RedirectToAction(nameof(EnterInput));
        }
        public async Task<IActionResult> RuleTransfer()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AccountInput()
        {
            string cardNo = HttpContext.Session.GetString("CardNo");
            var result = await _unitOfWork.CardRepository.GetCard(StaticDetails.CardAPIPath, cardNo, HttpContext.Session.GetString("JWToken"));
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> AccountInput(string AcountNoRecive)
        {

            var result=await _unitOfWork.AccountRepository.CheckAccountIsValid(StaticDetails.AccountAPIPath, AcountNoRecive, HttpContext.Session.GetString("JWToken"));
            if (result)
            {
                var account = await _unitOfWork.AccountRepository.GetAccount(StaticDetails.AccountAPIPath, AcountNoRecive, HttpContext.Session.GetString("JWToken"));
                return View("AcceptedAccountRecive", account);
            }
            return View("ReAccountInput");
        }
        
        public async Task<IActionResult> AmountInput(string name, string accountNo)
        {
            TransferViewModel obj = new TransferViewModel { Name = name, AccountNo = accountNo };         
            return View(obj);
        }
        
        
        public async Task<IActionResult> AcceptedTransfer(TransferViewModel transfer, string TransferAmount)
        {
            string cardNo = HttpContext.Session.GetString("CardNo");
            var resultCard = await _unitOfWork.CardRepository.GetCard(StaticDetails.CardAPIPath, cardNo, HttpContext.Session.GetString("JWToken"));

            if (String.IsNullOrEmpty(TransferAmount))
            {
                TempData["ErrorMessages"] = "Enter amount money you want to withdraw. Number you enter must be divisible to 50.0000.";
                return RedirectToAction(nameof(EnterInput));
            }
            while (TransferAmount.IndexOf(".") != -1)
            {
                TransferAmount = TransferAmount.Replace(".", "");
            }
            decimal TransferMoney = decimal.Parse(TransferAmount);
            var result = await _unitOfWork.AccountRepository.EnoughMoneyToTransfer(StaticDetails.AccountAPIPath, resultCard.AccountNo, TransferMoney, HttpContext.Session.GetString("JWToken"));
            if (result)
            {
                transfer.MoneyTransfer = TransferMoney;
                return View("AcceptedTransfer", transfer );
            }
            return View("ReAmountInput", transfer);
        }


        public async Task<IActionResult> Transfer(string name, string accountNo, decimal amount)
        {
            string cardNo = HttpContext.Session.GetString("CardNo");
            int ATMId = int.Parse(HttpContext.Session.GetString("ATMId"));
            var result = await _unitOfWork.CustomerRepository.Transfer(StaticDetails.CustomerAPIPath, ATMId, amount, cardNo, accountNo, HttpContext.Session.GetString("JWToken"));
            return View();
        }

        public async Task<IActionResult> Balance(string accountNo)
        {
            string cardNo = HttpContext.Session.GetString("CardNo");
            var result = await _unitOfWork.CustomerRepository.CheckBalance(StaticDetails.AccountAPIPath, cardNo, HttpContext.Session.GetString("JWToken"));
            return View(result);
        }
        public IActionResult NewPIN()
        {

            return View();
            
        }


        public IActionResult RePIN(string newPIN)
        {

            string oldPIN = HttpContext.Session.GetString("PIN");
            if (TempData.ContainsKey("newPIN"))
            {
                newPIN = TempData["newPIN"].ToString();
            }
            if (String.IsNullOrEmpty(newPIN))
            {
                TempData["ErrorMessages"] = "Enter a NEW PIN";
                return RedirectToAction(nameof(NewPIN));
            }
            if (newPIN.Length != 6)
            {
                TempData["ErrorMessages"] = "NEW PIN is 6 number";
                return RedirectToAction(nameof(NewPIN));
            }
            if (oldPIN != newPIN)
            {
                TempData["newPIN"] = newPIN;
                return View("RePIN");

            }
            else
            {
                TempData["ErrorMessages"] = "OLD PIN and NEW PIN can't coincide";
                return RedirectToAction(nameof(NewPIN));
            }

        }


        [HttpPost]
        public async Task<IActionResult> ChangePINSuccess(string rePIN)
        {
            string cardNo = HttpContext.Session.GetString("CardNo");
            int atmID = int.Parse(HttpContext.Session.GetString("ATMId"));
            string oldPIN = HttpContext.Session.GetString("PIN");
            string newPIN;
            
            if (TempData.ContainsKey("newPIN"))
            {
                newPIN = TempData["newPIN"].ToString();
                
                if (newPIN != rePIN)
                {
                    TempData["newPIN"] = newPIN;
                    TempData["ErrorMessages"] = "NEW PIN and RE-PIN don't match";
                    return RedirectToAction(nameof(RePIN));
                }
                if (String.IsNullOrEmpty(rePIN))
                {
                    TempData["newPIN"] = newPIN;
                    TempData["ErrorMessages"] = "Enter a RE-PIN";
                    return RedirectToAction(nameof(RePIN));
                }

                var status = await _unitOfWork.CustomerRepository.ChangePinAsync(StaticDetails.CustomerAPIPath, cardNo, oldPIN, newPIN, rePIN, atmID, HttpContext.Session.GetString("JWToken"));
                if (status)
                {
                    return View("ChangePINSuccess");
                }
                else
                {
                    TempData["newPIN"] = newPIN;
                    TempData["ErrorMessages"] = "Your PIN not changed";
                    return RedirectToAction(nameof(RePIN));
                }
            }
            return View("ChangePINSuccess");
            
        }
    }
}

FA.AtmSystem.Web/Controllers/LogViewHistoryController.cs
using FA.AtmSystem.Web.Infrastructures;
using Microsoft.AspNetCore.Mvc;

namespace FA.AtmSystem.Web.Controllers
{
    public class LogViewHistoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public LogViewHistoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetViewHistoryInADuration(int duration, int index = 0)
        {
            ViewBag.Duration = duration;
            ViewBag.Page = index;
            string cardNo = HttpContext.Session.GetString("CardNo");
            var result = await _unitOfWork.LogRepository.GetAllAsync(StaticDetails.LogAPIPath + "GetAllOfHistoryTransactions/" + cardNo + "/" + duration + "/" + index);

            return View(result);

        }
    }
}

FA.AtmSystem.Web/Views/ATM/ATMCardList.cshtml
@model IEnumerable<FA.AtmSystem.Core.Models.Card>

@{
    ViewData["Title"] = "ATMCardList";
}

<h1>ATMCardList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PIN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiredDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attempt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PIN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpiredDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attempt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Account.AccountNo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CardNo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CardNo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CardNo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FA.AtmSystem.Web/Views/ATM/EjectCard.cshtml
<h2 class="text-center">System does not reconize ATM Card</h2>
<h2 class="text-center">Eject Card...</h2>

FA.AtmSystem.Web/Views/ATM/Goodbye.cshtml
@{
    string ATMBranch = Context.Session.GetString("ATMBranch");
}
<h2>Thanks for using @ATMBranch</h2>
<h2>Goodbye!</h2>

FA.AtmSystem.Web/Views/ATM/Index.cshtml
<p class="text-center">Please select a transaction</p>
              <div style="padding: 17px;float: left;">
                <div>
                     <a class="btn btn-lg btn-padding-tran logout-tran btn-link-1" asp-controller="Customer" asp-action="Index">WithDraw</a>
                </div>
                <br>
                <div>
                  <a class="btn btn-lg btn-padding-tran logout-tran btn-link-2" asp-controller="Customer" asp-action="Balance">Check Balance</a>
                </div>
                <br>
                <div>
                  <a class="btn btn-lg btn-padding-tran logout-tran btn-link-3" asp-controller="Customer" asp-action="RuleTransfer">Transfer</a>
                </div>
              </div>

              <div style="padding: 17px" align="right">
                <div>
                  <a class="btn btn-lg btn-padding-tran logout-tran-right btn-link-4" asp-controller="LogViewHistory" asp-action="Index"> View History</a>
                </div>
                <br>
                <div>
                  <a class="btn btn-lg btn-padding-tran logout-tran-right btn-link-5" asp-action="NewPIN" asp-controller="Customer" > Change PIN</a>
                </div>
                <br>
                <div>
                  <a class="btn btn-lg btn-padding-tran logout-tran-right btn-link-6" asp-controller="ATM" asp-action="Logout"> Exit</a>
                </div>
              </div>

FA.AtmSystem.Web/Views/ATM/SwallowCard.cshtml
<h2 class="text-center">You entered PIN number wrong more than 3 times</h2>
<h2 class="text-center">Swallow Card...</h2>

FA.AtmSystem.Web/Views/ATM/ValidateCard.cshtml
@using FA.AtmSystem.Cards.ViewModels

@model CardValidateVM
@{
    ViewData["Title"] = "Validate Card";
}
<form method="post">
    <div class="text-center">
        <p>Enter Card Number</p>
        <div class="form-group col-4" >
            <input asp-for="CardNo" type="text" class="form-control input-number" style="font-weight: bolder; font-size:20px;width:250px;margin:auto"/>
            <button class="btn-link-enter " type="submit" value="Submit"  style="visibility:hidden">Enter</button>
        </div> 
        <p>then press Enter button</p>
    </div> 
</form>
       

FA.AtmSystem.Web/Views/ATM/ValidateCardPIN.cshtml
@using FA.AtmSystem.Cards.ViewModels
@model CardValidatePINVM
@{
    ViewData["Title"] = "ValidateCardPIN";
    var tempVal = TempData["Attempt"];
}

@if(tempVal != null)
{
    @if(tempVal.ToString() == "1")
    {
        <p class="text-center">You enter WRONG PIN Number</p>
    }
}


<form method="post" >
    <div class="text-center">
        <p>Enter Your PIN</p>
        <div class="form-group col-4" >
            <input asp-for="InputPIN" type="text" class="form-control input-number" style="font-weight: bolder; font-size:20px;width:250px;margin:auto"/>
            <span asp-validation-for="InputPIN" class="text-danger"></span>
            <input type="hidden" asp-for= "CardNo" value="@TempData["CardNo"]" />
            <button value="Submit" class="btn-link-enter btn-valid" style="visibility:hidden">Enter</button>
        </div> 
        <p>then press Enter button</p>
    </div> 
</form>

@section scripts {

    <script>

        //localStorage.setItem("linkToPage", "ATM/Index")    
        
    </script>

}

FA.AtmSystem.Web/Views/ATM/ValidateWait.cshtml
<div class="text-center">
     <h3>Validating ....</h3>
     
</div>

@section scripts {

    <script>
        //document.addEventListener("DOMContentLoaded",function(element){
        //    setTimeout(()=>{

        //        location.href=  "/Index"
                
        //    },5000)
        //});

    </script>

}